### ISSUE TITLE
AI設定について

### ISSUE THREAD

**Issue by timtaros** [sato-susumu/susumu_toolbox#8]
こんにちは。AIと音声会話ができるツールを探してたどり着きました。スムーズに動く理想のツールです！素晴らしいです！
AIのキャラ付けについての質問させてください。設定画面のAI設定で内容を書き換えても会話に反映されませんでした。user_dataのai_system_settings_default.txtはちゃんと書き換えられているのですが、何が原因なのでしょうか？どのようにすればAIのキャラ設定を変えられますか？
質問のためにGitHubに登録した初心者なので、質問場所や作法など間違っていたら申し訳ありません…
お手数をおかけしますがよろしくお願いいたします。

**Comment by sato-susumu** [comment]
使ってくれてありがとうございます！
そんなにベタ褒めされるとは思ってなかったですw
設定画面のAI設定が会話に反映されないのはバグです。
v0.1.1で修正したので、お手数ですがこちらで試してみてください。
(私もGitHub初心者で作法とかよくわかってないので何でも大丈夫です。)

**Comment by timtaros** [comment]
ご返信、ご対応ありがとうございます！
しかし、お恥ずかしいことにガチの初心者なので、Microsoft C++ Build Toolsは何とかインストールしたもののパッケージインストールの時点で何が何やらになってしまいました。
コマンドの叩き方がよくわからず…
せっかくご対応いただいたのに本当に申し訳ありません…

**Comment by sato-susumu** [comment]
間違えてドキュメントを古いバージョンに戻し過ぎていました。。。
余計な手間を取らせて、すみません。
前のバージョン(v0.1.0)と同じように、[リリースページ](https://github.com/sato-susumu/susumu_toolbox/releases)から`susumu_toolbox_0.1.1.zip`をダウンロードして解凍することで使用できます！

**Comment by timtaros** [comment]
無事に設定変更できました！ありがとうございます！！これでかわいい虚言癖ずんだもんに意味不明な返答をしてもらえます！！本当に助かりました！！
chatgptやVOICEVOXで、AIとおしゃべりする夢が叶いそうなのに自分に知識がなく困り果てていたので、こういうアプリを作って公開までしていただけて感謝です…
何も返すことができず恐縮ですが、これからも色々なプロンプトを試したりして楽しませていただきます…！ありがとうございました！

**Comment by sato-susumu** [comment]
無事動いて良かったです！
公開したソフトで楽しんでもらえるのが、何よりのお返しです！
